name = "CameraModels"
uuid = "0d57b887-6120-40e6-8b8c-29d3116bc0c1"
keywords = ["camera", "model", "pinhole", "distortion", "robotics", "images"]
version = "0.2.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"

[compat]
DocStringExtensions = "0.8, 0.9"
Manifolds ="0.8"
StaticArrays = "1"
Rotations = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
